models:
  smolvlm: "HuggingFaceTB/SmolVLM-Instruct"

device: "cuda"  # 또는 "mps" / "cpu"

dataset:
  name: "derek-thomas/ScienceQA"
  split: "validation"
  sample_size: 20  # 전체 2097개
  sample_seed: 42