models:
  smolvlm: "HuggingFaceTB/SmolVLM2-2.2B-Instruct"

device: "cuda"  # 또는 "mps" / "cpu"

dataset:
  name: "lmms-lab/DocVQA"  # 이 부분만 변경
  split: "validation"
  sample_size: 1000 #1000
  sample_seed: 42
